// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgRegisterInterchainQuery } from "./types/interchainqueries/tx";
import { MsgSubmitQueryResult } from "./types/interchainqueries/tx";
import { MsgRemoveInterchainQueryRequest } from "./types/interchainqueries/tx";

import { RegisteredQuery as typeRegisteredQuery} from "./types"
import { KVKey as typeKVKey} from "./types"
import { Params as typeParams} from "./types"
import { Transaction as typeTransaction} from "./types"
import { QueryResult as typeQueryResult} from "./types"
import { StorageValue as typeStorageValue} from "./types"
import { Block as typeBlock} from "./types"
import { TxValue as typeTxValue} from "./types"

export { MsgRegisterInterchainQuery, MsgSubmitQueryResult, MsgRemoveInterchainQueryRequest };

type sendMsgRegisterInterchainQueryParams = {
  value: MsgRegisterInterchainQuery,
  fee?: StdFee,
  memo?: string
};

type sendMsgSubmitQueryResultParams = {
  value: MsgSubmitQueryResult,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveInterchainQueryRequestParams = {
  value: MsgRemoveInterchainQueryRequest,
  fee?: StdFee,
  memo?: string
};


type msgRegisterInterchainQueryParams = {
  value: MsgRegisterInterchainQuery,
};

type msgSubmitQueryResultParams = {
  value: MsgSubmitQueryResult,
};

type msgRemoveInterchainQueryRequestParams = {
  value: MsgRemoveInterchainQueryRequest,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgRegisterInterchainQuery({ value, fee, memo }: sendMsgRegisterInterchainQueryParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegisterInterchainQuery: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegisterInterchainQuery({ value: MsgRegisterInterchainQuery.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegisterInterchainQuery: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSubmitQueryResult({ value, fee, memo }: sendMsgSubmitQueryResultParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSubmitQueryResult: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSubmitQueryResult({ value: MsgSubmitQueryResult.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSubmitQueryResult: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveInterchainQueryRequest({ value, fee, memo }: sendMsgRemoveInterchainQueryRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveInterchainQueryRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRemoveInterchainQueryRequest({ value: MsgRemoveInterchainQueryRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveInterchainQueryRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgRegisterInterchainQuery({ value }: msgRegisterInterchainQueryParams): EncodeObject {
			try {
				return { typeUrl: "/neutron.interchainqueries.MsgRegisterInterchainQuery", value: MsgRegisterInterchainQuery.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegisterInterchainQuery: Could not create message: ' + e.message)
			}
		},
		
		msgSubmitQueryResult({ value }: msgSubmitQueryResultParams): EncodeObject {
			try {
				return { typeUrl: "/neutron.interchainqueries.MsgSubmitQueryResult", value: MsgSubmitQueryResult.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSubmitQueryResult: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveInterchainQueryRequest({ value }: msgRemoveInterchainQueryRequestParams): EncodeObject {
			try {
				return { typeUrl: "/neutron.interchainqueries.MsgRemoveInterchainQueryRequest", value: MsgRemoveInterchainQueryRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveInterchainQueryRequest: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						RegisteredQuery: getStructure(typeRegisteredQuery.fromPartial({})),
						KVKey: getStructure(typeKVKey.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						Transaction: getStructure(typeTransaction.fromPartial({})),
						QueryResult: getStructure(typeQueryResult.fromPartial({})),
						StorageValue: getStructure(typeStorageValue.fromPartial({})),
						Block: getStructure(typeBlock.fromPartial({})),
						TxValue: getStructure(typeTxValue.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			NeutronInterchainqueries: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;